name       : gengetopt
version    : '2.23'
release    : 5
source     :
    - https://ftp.gnu.org/gnu/gengetopt/gengetopt-2.23.tar.xz : b941aec9011864978dd7fdeb052b1943535824169d2aa2b0e7eae9ab807584ac
license    : GPL-3.0
component  : programming.tools
summary    : Gengetopt is a tool to generate C code to parse the command line arguments argc and argv that are part of every C or C++ program.
description: |
    Gengetopt is a tool to generate C code to parse the command line arguments argc and argv that are part of every C or C++ program.
builddeps  :
    - help2man
setup      : |
    sed -i '15i#include <cstring>' src/fileutils.cpp
    %reconfigure
build      : |
    CXXFLAGS+=" -std=gnu++98"
    %make -j1
install    : |
    %make_install
