name       : gengetopt
version    : 2.22
release    : 1
source     :
    - ftp://ftp.gnu.org/gnu/gengetopt/gengetopt-2.22.tar.gz : b605555e41e9bf7e852a37b051e6a49014e561f21290680e3a60c279488d417e
license    : GPL-3.0
component  : programming.tool
summary    : Gengetopt is a tool to generate C code to parse the command line arguments argc and argv that are part of every C or C++ program.
description: |
    Gengetopt is a tool to generate C code to parse the command line arguments argc and argv that are part of every C or C++ program.
builddeps  :
    - help2man
setup      : |
    sed -i '15i#include <cstring>' src/fileutils.cpp
    %configure
build      : |
    CXXFLAGS+=" -std=gnu++98"
    %make
install    : |
    %make_install
